### ISSUE TITLE
Scripts in multiple places

### ISSUE THREAD

**Issue by benhager** [tjluoma/di#8]
Hey TJ,

I made be mistaken here, but I think the purpose of Pull Request #5 was to move all the scripts to the /di-scripts folder and only keep them there. It looks like at the moment, all the scripts are at the root level and in the /di-scripts folder.  Is that an issue or did I miss something?

Thanks and love the scripts!!
-Ben

**Comment by tjluoma** [comment]
Oh, jiminy crap. That's what happened. OK, I misunderstood freaked out a little that they were all gone, or so it seemed.

I'd rather not move them all into a sub-folder because that will break all the commit history for them. If others want to move them there on their local system, that's fine, but I'm going to leave mine at the top level and get rid of the sub-folder.

Thanks for the help.

**Comment by benhager** [comment]
Sounds good, either way works for me... just surprised me that there were 2 copies of everything. All good now. 👍

**Comment by superbimble** [comment]
That's my bad, sorry.  I moved them just to make life easier for the automation script. I'll have a re-think and fix it today or tomorrow.

**Comment by tjluoma** [comment]
You should be able to match them using 

```
  di-.*\.sh
```

as a regex, if that helps.
